// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: channels.sql

package database

import (
	"context"
)

const createChannel = `-- name: CreateChannel :one
INSERT INTO channels(id, title, handle, created_at)
VALUES (
	?,
	?,
	?,
        datetime('now')
)
RETURNING id, handle, title, created_at, frequency, videos_since_post
`

type CreateChannelParams struct {
	ID     string
	Title  string
	Handle string
}

func (q *Queries) CreateChannel(ctx context.Context, arg CreateChannelParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, createChannel, arg.ID, arg.Title, arg.Handle)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.CreatedAt,
		&i.Frequency,
		&i.VideosSincePost,
	)
	return i, err
}

const deleteChannel = `-- name: DeleteChannel :one
DELETE FROM channels
WHERE id = ?
RETURNING id, handle, title, created_at, frequency, videos_since_post
`

func (q *Queries) DeleteChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, deleteChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.CreatedAt,
		&i.Frequency,
		&i.VideosSincePost,
	)
	return i, err
}

const findChannel = `-- name: FindChannel :one
SELECT id, handle, title, created_at, frequency, videos_since_post FROM channels
WHERE id = ?
`

func (q *Queries) FindChannel(ctx context.Context, id string) (Channel, error) {
	row := q.db.QueryRowContext(ctx, findChannel, id)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.CreatedAt,
		&i.Frequency,
		&i.VideosSincePost,
	)
	return i, err
}

const getChannels = `-- name: GetChannels :many
SELECT id, handle, title, created_at, frequency, videos_since_post FROM channels
`

func (q *Queries) GetChannels(ctx context.Context) ([]Channel, error) {
	rows, err := q.db.QueryContext(ctx, getChannels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Channel
	for rows.Next() {
		var i Channel
		if err := rows.Scan(
			&i.ID,
			&i.Handle,
			&i.Title,
			&i.CreatedAt,
			&i.Frequency,
			&i.VideosSincePost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChannelFreq = `-- name: UpdateChannelFreq :one
UPDATE channels
SET frequency = ?
WHERE id = ?
RETURNING id, handle, title, created_at, frequency, videos_since_post
`

type UpdateChannelFreqParams struct {
	Frequency int64
	ID        string
}

func (q *Queries) UpdateChannelFreq(ctx context.Context, arg UpdateChannelFreqParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateChannelFreq, arg.Frequency, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.CreatedAt,
		&i.Frequency,
		&i.VideosSincePost,
	)
	return i, err
}

const updateVideosSincePost = `-- name: UpdateVideosSincePost :one
UPDATE channels
SET videos_since_post = ?
WHERE id = ?
RETURNING id, handle, title, created_at, frequency, videos_since_post
`

type UpdateVideosSincePostParams struct {
	VideosSincePost int64
	ID              string
}

func (q *Queries) UpdateVideosSincePost(ctx context.Context, arg UpdateVideosSincePostParams) (Channel, error) {
	row := q.db.QueryRowContext(ctx, updateVideosSincePost, arg.VideosSincePost, arg.ID)
	var i Channel
	err := row.Scan(
		&i.ID,
		&i.Handle,
		&i.Title,
		&i.CreatedAt,
		&i.Frequency,
		&i.VideosSincePost,
	)
	return i, err
}
