// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Channel struct {
	ID        string
	Handle    string
	Title     string
	CreatedAt sql.NullTime
}

type Comment struct {
	ID        string
	Likes     int64
	QuoteID   int64
	CreatedAt sql.NullTime
}

type Cornucopium struct {
	ID         int64
	Quote      string
	Author     string
	Categories string
	CreatedAt  sql.NullTime
}

type Login struct {
	ID        string
	CreatedAt time.Time
	LastLogin time.Time
}

type Quotum struct {
	ID        string
	Quota     int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Reply struct {
	ID        string
	Likes     int64
	QuoteID   int64
	CreatedAt sql.NullTime
	VideoID   string
}

type Video struct {
	ID string
}
