// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package database

import (
	"database/sql"
	"time"
)

type Cornucopium struct {
	ID         interface{}
	Quote      string
	Author     string
	Categories string
	CreatedAt  sql.NullTime
}

type Login struct {
	ID        string
	CreatedAt time.Time
	LastLogin time.Time
}

type Reply struct {
	ID        string
	Likes     int64
	QuoteID   int64
	CreatedAt sql.NullTime
	VideoID   sql.NullString
}

type Video struct {
	ID string
}
