// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: replies.sql

package database

import (
	"context"
	"database/sql"
)

const getPopularReplies = `-- name: GetPopularReplies :many
SELECT replies.id, replies.likes, replies.quote_id, replies.created_at, replies.video_id, cornucopia.quote, cornucopia.author
FROM replies JOIN cornucopia ON replies.quote_id = cornucopia.id
ORDER BY replies.likes DESC
`

type GetPopularRepliesRow struct {
	ID        string
	Likes     int64
	QuoteID   int64
	CreatedAt sql.NullTime
	VideoID   string
	Quote     string
	Author    string
}

func (q *Queries) GetPopularReplies(ctx context.Context) ([]GetPopularRepliesRow, error) {
	rows, err := q.db.QueryContext(ctx, getPopularReplies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPopularRepliesRow
	for rows.Next() {
		var i GetPopularRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.Likes,
			&i.QuoteID,
			&i.CreatedAt,
			&i.VideoID,
			&i.Quote,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getReplies = `-- name: GetReplies :many
SELECT id, likes, quote_id, created_at, video_id FROM replies
`

func (q *Queries) GetReplies(ctx context.Context) ([]Reply, error) {
	rows, err := q.db.QueryContext(ctx, getReplies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Reply
	for rows.Next() {
		var i Reply
		if err := rows.Scan(
			&i.ID,
			&i.Likes,
			&i.QuoteID,
			&i.CreatedAt,
			&i.VideoID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkVideo = `-- name: LinkVideo :one
UPDATE replies
SET video_id = ?
WHERE id = ?
RETURNING id, likes, quote_id, created_at, video_id
`

type LinkVideoParams struct {
	VideoID string
	ID      string
}

func (q *Queries) LinkVideo(ctx context.Context, arg LinkVideoParams) (Reply, error) {
	row := q.db.QueryRowContext(ctx, linkVideo, arg.VideoID, arg.ID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.Likes,
		&i.QuoteID,
		&i.CreatedAt,
		&i.VideoID,
	)
	return i, err
}

const storeReply = `-- name: StoreReply :one
INSERT INTO replies(id, likes, quote_id, video_id, created_at)
VALUES (
	?,
	?,
	?,
	?,
        datetime('now')
)
RETURNING id, likes, quote_id, created_at, video_id
`

type StoreReplyParams struct {
	ID      string
	Likes   int64
	QuoteID int64
	VideoID string
}

func (q *Queries) StoreReply(ctx context.Context, arg StoreReplyParams) (Reply, error) {
	row := q.db.QueryRowContext(ctx, storeReply,
		arg.ID,
		arg.Likes,
		arg.QuoteID,
		arg.VideoID,
	)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.Likes,
		&i.QuoteID,
		&i.CreatedAt,
		&i.VideoID,
	)
	return i, err
}

const updateReplyLikes = `-- name: UpdateReplyLikes :one
UPDATE replies
SET likes = ?
WHERE id = ?
RETURNING id, likes, quote_id, created_at, video_id
`

type UpdateReplyLikesParams struct {
	Likes int64
	ID    string
}

func (q *Queries) UpdateReplyLikes(ctx context.Context, arg UpdateReplyLikesParams) (Reply, error) {
	row := q.db.QueryRowContext(ctx, updateReplyLikes, arg.Likes, arg.ID)
	var i Reply
	err := row.Scan(
		&i.ID,
		&i.Likes,
		&i.QuoteID,
		&i.CreatedAt,
		&i.VideoID,
	)
	return i, err
}
