// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: tasks.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const claimTask = `-- name: ClaimTask :one
UPDATE tasks
SET status = 'running', attempts = attempts + 1, claimed_at = datetime('now')
WHERE id = ? AND status = 'pending'
RETURNING id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at
`

func (q *Queries) ClaimTask(ctx context.Context, id string) (Task, error) {
	row := q.db.QueryRowContext(ctx, claimTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChannelID,
		&i.QuoteID,
		&i.Status,
		&i.Attempts,
		&i.QuotaCost,
		&i.CommentID,
		&i.Error,
		&i.CreatedAt,
		&i.ActiveAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeTask = `-- name: CompleteTask :one
UPDATE tasks
SET status = 'done', comment_id = ?, completed_at = datetime('now'), error = NULL, claimed_at = NULL
WHERE id = ?
RETURNING id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at
`

type CompleteTaskParams struct {
	CommentID sql.NullString
	ID        string
}

func (q *Queries) CompleteTask(ctx context.Context, arg CompleteTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, completeTask, arg.CommentID, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChannelID,
		&i.QuoteID,
		&i.Status,
		&i.Attempts,
		&i.QuotaCost,
		&i.CommentID,
		&i.Error,
		&i.CreatedAt,
		&i.ActiveAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const countTasksByStatus = `-- name: CountTasksByStatus :many
SELECT status, COUNT(*) AS total
FROM tasks
GROUP BY status
`

type CountTasksByStatusRow struct {
	Status string
	Total  int64
}

func (q *Queries) CountTasksByStatus(ctx context.Context) ([]CountTasksByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, countTasksByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTasksByStatusRow
	for rows.Next() {
		var i CountTasksByStatusRow
		if err := rows.Scan(&i.Status, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (id, video_id, channel_id, quote_id, quota_cost, status, created_at, active_at)
VALUES (
	?,
	?,
	?,
	?,
	?,
	'pending',
	datetime('now'),
	?
)
RETURNING id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at
`

type CreateTaskParams struct {
	ID        string
	VideoID   string
	ChannelID string
	QuoteID   int64
	QuotaCost int64
	ActiveAt  time.Time
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, createTask,
		arg.ID,
		arg.VideoID,
		arg.ChannelID,
		arg.QuoteID,
		arg.QuotaCost,
		arg.ActiveAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChannelID,
		&i.QuoteID,
		&i.Status,
		&i.Attempts,
		&i.QuotaCost,
		&i.CommentID,
		&i.Error,
		&i.CreatedAt,
		&i.ActiveAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteOldTasks = `-- name: DeleteOldTasks :many
DELETE FROM tasks
WHERE status IN ('done', 'failed') AND completed_at < ?
RETURNING id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at
`

func (q *Queries) DeleteOldTasks(ctx context.Context, completedAt sql.NullTime) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, deleteOldTasks, completedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChannelID,
			&i.QuoteID,
			&i.Status,
			&i.Attempts,
			&i.QuotaCost,
			&i.CommentID,
			&i.Error,
			&i.CreatedAt,
			&i.ActiveAt,
			&i.ClaimedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const failTask = `-- name: FailTask :one
UPDATE tasks
SET status = 'failed', error = ?, completed_at = datetime('now'), claimed_at = NULL
WHERE id = ?
RETURNING id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at
`

type FailTaskParams struct {
	Error sql.NullString
	ID    string
}

func (q *Queries) FailTask(ctx context.Context, arg FailTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, failTask, arg.Error, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChannelID,
		&i.QuoteID,
		&i.Status,
		&i.Attempts,
		&i.QuotaCost,
		&i.CommentID,
		&i.Error,
		&i.CreatedAt,
		&i.ActiveAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const findTaskByVideo = `-- name: FindTaskByVideo :one
SELECT id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at FROM tasks
WHERE video_id = ?
`

func (q *Queries) FindTaskByVideo(ctx context.Context, videoID string) (Task, error) {
	row := q.db.QueryRowContext(ctx, findTaskByVideo, videoID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChannelID,
		&i.QuoteID,
		&i.Status,
		&i.Attempts,
		&i.QuotaCost,
		&i.CommentID,
		&i.Error,
		&i.CreatedAt,
		&i.ActiveAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDueTasks = `-- name: GetDueTasks :many
SELECT id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at FROM tasks
WHERE status = 'pending' AND active_at <= datetime('now')
ORDER BY active_at
LIMIT ?
`

func (q *Queries) GetDueTasks(ctx context.Context, limit int64) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getDueTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChannelID,
			&i.QuoteID,
			&i.Status,
			&i.Attempts,
			&i.QuotaCost,
			&i.CommentID,
			&i.Error,
			&i.CreatedAt,
			&i.ActiveAt,
			&i.ClaimedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTasks = `-- name: GetPendingTasks :many
SELECT id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at FROM tasks
WHERE status = 'pending'
ORDER BY active_at
`

func (q *Queries) GetPendingTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getPendingTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChannelID,
			&i.QuoteID,
			&i.Status,
			&i.Attempts,
			&i.QuotaCost,
			&i.CommentID,
			&i.Error,
			&i.CreatedAt,
			&i.ActiveAt,
			&i.ClaimedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentTasks = `-- name: GetRecentTasks :many
SELECT tasks.id, tasks.video_id, tasks.channel_id, tasks.quote_id, tasks.status, tasks.attempts, tasks.quota_cost, tasks.comment_id, tasks.error, tasks.created_at, tasks.active_at, tasks.claimed_at, tasks.completed_at, cornucopia.quote, cornucopia.author
FROM tasks LEFT JOIN cornucopia ON tasks.quote_id = cornucopia.id
ORDER BY tasks.created_at DESC
LIMIT ?
`

type GetRecentTasksRow struct {
	ID          string
	VideoID     string
	ChannelID   string
	QuoteID     int64
	Status      string
	Attempts    int64
	QuotaCost   int64
	CommentID   sql.NullString
	Error       sql.NullString
	CreatedAt   time.Time
	ActiveAt    time.Time
	ClaimedAt   sql.NullTime
	CompletedAt sql.NullTime
	Quote       sql.NullString
	Author      sql.NullString
}

func (q *Queries) GetRecentTasks(ctx context.Context, limit int64) ([]GetRecentTasksRow, error) {
	rows, err := q.db.QueryContext(ctx, getRecentTasks, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentTasksRow
	for rows.Next() {
		var i GetRecentTasksRow
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChannelID,
			&i.QuoteID,
			&i.Status,
			&i.Attempts,
			&i.QuotaCost,
			&i.CommentID,
			&i.Error,
			&i.CreatedAt,
			&i.ActiveAt,
			&i.ClaimedAt,
			&i.CompletedAt,
			&i.Quote,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRunningTasks = `-- name: GetRunningTasks :many
SELECT id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at FROM tasks
WHERE status = 'running'
ORDER BY claimed_at
`

func (q *Queries) GetRunningTasks(ctx context.Context) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, getRunningTasks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChannelID,
			&i.QuoteID,
			&i.Status,
			&i.Attempts,
			&i.QuotaCost,
			&i.CommentID,
			&i.Error,
			&i.CreatedAt,
			&i.ActiveAt,
			&i.ClaimedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const releaseStaleTasks = `-- name: ReleaseStaleTasks :many
UPDATE tasks
SET status = 'pending', claimed_at = NULL
WHERE status = 'running' AND (claimed_at IS NULL OR claimed_at <= ?)
RETURNING id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at
`

func (q *Queries) ReleaseStaleTasks(ctx context.Context, claimedAt sql.NullTime) ([]Task, error) {
	rows, err := q.db.QueryContext(ctx, releaseStaleTasks, claimedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Task
	for rows.Next() {
		var i Task
		if err := rows.Scan(
			&i.ID,
			&i.VideoID,
			&i.ChannelID,
			&i.QuoteID,
			&i.Status,
			&i.Attempts,
			&i.QuotaCost,
			&i.CommentID,
			&i.Error,
			&i.CreatedAt,
			&i.ActiveAt,
			&i.ClaimedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const retryTask = `-- name: RetryTask :one
UPDATE tasks
SET status = 'pending', error = ?, active_at = ?, claimed_at = NULL
WHERE id = ?
RETURNING id, video_id, channel_id, quote_id, status, attempts, quota_cost, comment_id, error, created_at, active_at, claimed_at, completed_at
`

type RetryTaskParams struct {
	Error    sql.NullString
	ActiveAt time.Time
	ID       string
}

func (q *Queries) RetryTask(ctx context.Context, arg RetryTaskParams) (Task, error) {
	row := q.db.QueryRowContext(ctx, retryTask, arg.Error, arg.ActiveAt, arg.ID)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.VideoID,
		&i.ChannelID,
		&i.QuoteID,
		&i.Status,
		&i.Attempts,
		&i.QuotaCost,
		&i.CommentID,
		&i.Error,
		&i.CreatedAt,
		&i.ActiveAt,
		&i.ClaimedAt,
		&i.CompletedAt,
	)
	return i, err
}

const sumPendingQuota = `-- name: SumPendingQuota :one
SELECT COALESCE(SUM(quota_cost), 0) AS reserved
FROM tasks
WHERE status IN ('pending', 'running')
`

func (q *Queries) SumPendingQuota(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, sumPendingQuota)
	var reserved interface{}
	err := row.Scan(&reserved)
	return reserved, err
}
